#!/usr/bin/ env python3
#coding = utf-8
import matplotlib.pyplot as plt
import numpy as np

#主要使用plt选择对象,这是面向过程的绘图方法

#定义函数
x = np.linspace(-4*np.pi,4*np.pi,1000 )
a = np.sin(x)*np.cos(x)

#定义画布，绘制图像
ax = plt.figure(figsize=(8,4), dpi=100)
plt.plot(x,a,color='red',label=r'$y=\sin(x)\cos(x)$')
#显示图例
plt.legend(loc=3)

#指定轴标签的位置
xticks = np.arange(-2*np.pi,3*np.pi,np.pi/2)
yticks = np.arange(-1,1.5,0.5)
#设置轴标签内容
plt.xticks(xticks,[r'$2\pi$',r'$ -\frac{3\pi}{2}$','$-\pi$',r'$ -\frac{\pi}{2}$',r'o', r'$ \frac{\pi}{2}$','$\pi$',r'$ \frac{3\pi}{2}$','$2\pi$'])
plt.yticks(yticks,['-1','-0.5','0.0','0.5','1.0'],fontsize=4)

plt.xlim(-11,11,1.0)
plt.ylim(-1.5,1.5)

#设置图表标题
plt.title(r'$y=\sin(x)\cos(x)$-graph')
plt.rcParams['font.sans-serif']=['SimHei'] #用来正常显示中文标签
plt.rcParams['axes.unicode_minus']=False #用来正常显示负号

#获取绘图对象的操作
ax = plt.gca()
#去掉边框
ax.spines['top'].set_color('none')
ax.spines['right'].set_color('none')
#移位置，设为原点相交
ax.xaxis.set_ticks_position('bottom')
ax.spines['bottom'].set_position(('data',0))
ax.yaxis.set_ticks_position('left')
ax.spines['left'].set_position(('data',0))

#设置箭头
plt.annotate('',xy=(0,1.5),xytext=(0,1.4), fontsize=8,
             arrowprops=dict(facecolor='black',headwidth=4))
plt.annotate('',xy=(11.0,0),xytext=(10.9,0), fontsize=4,
             arrowprops=dict(facecolor='black',headwidth=4))


#添加文字
plt.text(1,1,u'$y=\sin(x)\cos(x)$')
plt.text(0,0,'0')
plt.savefig(u'../savefig/rectangular_coordirate-y=sin(x)cos(x).png')

plt.show()

